services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
